error boundry, bug fixes and audio library add

diff --git a/App/.run/adb-reverse b/App/.run/adb-reverse
--- a/App/.run/adb-reverse
+++ b/App/.run/adb-reverse
@@ -10,25 +10,38 @@ ABD_PATH="${ANDROID_HOME}/platform-tools"
 [[ -f .npmrc ]] && source .npmrc
 [[ -f .env ]] && source .env
 
-# REACTOTRON
-[[ ! -z $RUN_REACT_REACTOTRON ]] &&  echo "Setting TCP:9090 For: 'REACTOTRON'" && ${ABD_PATH}/adb reverse tcp:9090 tcp:9090
-# REACT DEVTOOLS
-[[ ! -z $RUN_REACT_DEVTOOLS ]] &&  echo "Setting TCP:8097 For: 'REACT-DEVTOOLS'" && ${ABD_PATH}/adb reverse tcp:8097 tcp:8097
-# CHROME
-[[ ! -z $RUN_CHROMEDEVTOOLS ]] &&  echo "Setting TCP:8081 For: 'CHROME-DEVTOOLS'" && ${ABD_PATH}/adb reverse tcp:8081 tcp:8081
-# REACT DEBUGGER
-[[ ! -z $RUN_REACT_DEBUGGER ]] &&  echo "Setting TCP:8081 For: 'REACT-DEBUGGER'" && ${ABD_PATH}/adb reverse tcp:8081 tcp:8081
 
 # REACT-NATIVE CLI
-echo "Setting TCP:19001 For: 'EXPO-SERVER'"
+echo "Setting TCP:19001 For [EXPO-SERVER]"
 ${ABD_PATH}/adb reverse tcp:19000 tcp:19000
 
-echo "Setting TCP:19000 For: 'EXPO-BUNDLER'"
+ERROR_CODE="$?"
+[[ $ERROR_CODE > 0 ]] && echo "Problem with tcp reserve: $ERROR_CODE - exiting..." && exit ${ERROR_CODE}
+
+echo "Setting TCP:19000 For [EXPO-BUNDLER]"
 ${ABD_PATH}/adb reverse tcp:19001 tcp:19001
 
-echo "Setting TCP:19000 For: 'EXPO-BUNDLER'"
+echo "Setting TCP:19000 For [EXPO-BUNDLER]"
 ${ABD_PATH}/adb reverse tcp:19003 tcp:19003
+
+
+
+# REACTOTRON
+[[ ! -z $RUN_REACT_REACTOTRON ]] &&  echo "Setting TCP:9090 For [REACTOTRON]" && ${ABD_PATH}/adb reverse tcp:9090 tcp:9090
+# REACT DEVTOOLS
+[[ ! -z $RUN_REACT_DEVTOOLS ]] &&  echo "Setting TCP:8097 For [REACT-DEVTOOLS]" && ${ABD_PATH}/adb reverse tcp:8097 tcp:8097
+# CHROME
+[[ ! -z $RUN_CHROMEDEVTOOLS ]] &&  echo "Setting TCP:8081 For [CHROME-DEVTOOLS]" && ${ABD_PATH}/adb reverse tcp:8081 tcp:8081
+# REACT DEBUGGER
+[[ ! -z $RUN_REACT_DEBUGGER ]] &&  echo "Setting TCP:8081 For [REACT-DEBUGGER]" && ${ABD_PATH}/adb reverse tcp:8081 tcp:8081
+
+
+ERROR_CODE="$?"
+[[ $ERROR_CODE > 0 ]] && echo "Problem with tcp reserve: $ERROR_CODE - exiting..." && exit ${ERROR_CODE}
 
 
 echo -e "\n\tREVERSE PORT LIST\n---------------------------------"
 ${ABD_PATH}/adb reverse --list
+
+
+exit 0
diff --git a/App/.run/dev b/App/.run/dev
--- a/App/.run/dev
+++ b/App/.run/dev
@@ -18,6 +18,8 @@ unset REACT_EDITOR
 unset REACT_DEBUGGER
 set -a REACT_DEBUGGER
 
+
+EXPO_HOST="localhost"
 BASE_DIR="$(npm prefix)"
 ABD_PATH="${ANDROID_HOME}/platform-tools"
 
@@ -26,17 +28,23 @@ ABD_PATH="${ANDROID_HOME}/platform-tools"
 
 NODE_ENV="development"
 
+echo "Settings up device:"
+
 echo "Checking Android path ..."
 
 [[ -z $ANDROID_HOME ]] && echo 'ANDROID_HOME is not set. Skipping command' && exit 0
 
 npm run adb:reverse
 
+# TRYING TO CATCH ERRORS HERE SO WE CAN RECONNECT DEVICES
+# BEFORE EXPO FAILS TO CONNECT AND WE END UP IN A BAD STATE.
+[[ $? > 0 ]] && echo "Problem Connecting to device: $? - exiting early..." && exit 0
+
 echo "Settings up additional devtools..."
 
 # REACTOTRON
 if [ ! -z $RUN_REACT_REACTOTRON ]; then
-  npm run util:reactotron &
+  npm run react:reactotron &
 fi
 
 # REACT DEBUGGER
@@ -52,6 +60,7 @@ fi
 echo "
   APP_DEBUG_APPDATA  ${APP_DEBUG_APPDATA}
   EXPO_DEBUG  ${EXPO_DEBUG}
+  EXPO_HOST ${EXPO_HOST}
   NODE_DEBUG  ${NODE_DEBUG}
   NODE_ENV  ${NODE_ENV}
   NODE_OPTIONS  ${NODE_OPTIONS}
@@ -82,5 +91,5 @@ EXPO_DEBUG="${EXPO_DEBUG}" \
     --no-minify \
     --no-https \
     --dev \
-    --host localhost \
+    --host ${EXPO_HOST} \
     --android
