Fixed issues from last update to sdk 35

diff --git a/App/.run/adb-reverse b/App/.run/adb-reverse
--- a/App/.run/adb-reverse
+++ b/App/.run/adb-reverse
@@ -15,21 +15,23 @@ ABD_PATH="${ANDROID_HOME}/platform-tools"
 echo "Setting TCP:19000 For [EXPO-SERVER]"
 ${ABD_PATH}/adb reverse tcp:19000 tcp:19000
 
-ERROR_CODE="$?"
-[[ $ERROR_CODE > 0 ]] && echo "Problem with tcp reserve: $ERROR_CODE - exiting..." && exit ${ERROR_CODE}
+# ERROR_CODE="$?"
+# [[ $ERROR_CODE > 0 ]] && echo "Problem with tcp reserve: $ERROR_CODE - exiting..." && exit ${ERROR_CODE}
+#
+# echo "Setting TCP:19001 For [EXPO-BUNDLER]"
+# ${ABD_PATH}/adb reverse tcp:19001 tcp:19001
+#
+# echo "Setting TCP:19003 For [EXPO-BUNDLER]"
+# ${ABD_PATH}/adb reverse tcp:19003 tcp:19003
+#
+# echo "Setting TCP:19002 For [EXPO-DEVTOOLS]"
+# ${ABD_PATH}/adb reverse tcp:19003 tcp:19002
+#
+# echo "Setting TCP:19005 For [METRO BUNDLER]"
+# ${ABD_PATH}/adb reverse tcp:19004 tcp:19004
 
-echo "Setting TCP:19001 For [EXPO-BUNDLER]"
-${ABD_PATH}/adb reverse tcp:19001 tcp:19001
 
-echo "Setting TCP:19003 For [EXPO-BUNDLER]"
-${ABD_PATH}/adb reverse tcp:19003 tcp:19003
-
-echo "Setting TCP:19005 For [METRO BUNDLER]
-]"
-${ABD_PATH}/adb reverse tcp:19004 tcp:19004
-
-
-
+exit 0
 # REACTOTRON
 [[ ! -z $RUN_REACT_REACTOTRON ]] &&  echo "Setting TCP:9090 For [REACTOTRON]" && ${ABD_PATH}/adb reverse tcp:9090 tcp:9090
 # REACT DEVTOOLS
@@ -40,8 +42,8 @@ ${ABD_PATH}/adb reverse tcp:19004 tcp:19004
 [[ ! -z $RUN_REACT_DEBUGGER ]] &&  echo "Setting TCP:8081 For [REACT-DEBUGGER]" && ${ABD_PATH}/adb reverse tcp:8081 tcp:8081
 
 
-ERROR_CODE="$?"
-[[ $ERROR_CODE > 0 ]] && echo "Problem with tcp reserve: $ERROR_CODE - exiting..." && exit ${ERROR_CODE}
+#ERROR_CODE="$?"
+#[[ $ERROR_CODE > 0 ]] && echo "Problem with tcp reserve: $ERROR_CODE - exiting..." && exit ${ERROR_CODE}
 
 
 echo -e "\n\tREVERSE PORT LIST\n---------------------------------"
